site_name: HASS.Agent
site_description: Documentation for the HASS.Agent project, a Windows-based client for Home Assistant. Provides notifications, quick actions, commands, sensors and more.
site_author: LAB02-Research

theme:
    name: readthedocs

nav:
    - Home: index.md
    - 'introduction.md'
    - 'installation.md'
    - 'configuration.md'
    - 'installation-and-configuration-summary.md'
    - 'updating.md'
    - 'usage.md'
    - 'clean-slate.md'
    - 'performance-counter-debugging.md'
    - 'Examples':
      - Misc Examples: 'sensor-command-automation-and-script-examples.md'
      - WMI Examples: 'wmi-examples.md'
      - ActiveWindowSensor - Multiple Processes: 'examples/activewindowsensor-multiple-processes.md'
      - Adjust Screen Brightness: 'examples/adjust-screen-brightness.md'
      - PC Card: 'examples/pc-card.md'
    - 'translating.md'
    - 'Commands':
      - 'commands/command-basics.md'
      - 'commands/actions-usage-and-examples.md'
    - 'Media Player':
      - 'mediaplayer/mediaplayer-usage-and-examples.md'
    - 'Notifications':
      - 'notifications/notification-usage-and-examples.md'
      - 'notifications/notification-debugging-client-side.md'
      - 'notifications/notification-debugging-ha-side.md'
      - 'notifications/notification-debugging-ssl.md'
    - 'Development':
      - 'development/introduction.md'
      - 'development/commands.md'
      - 'development/sensors.md'
